vim.cmd[[nmap <silent><leader>rn <Plug>(coc-rename)]]
vim.cmd[[nmap <silent><leader>jd <Plug>(coc-definition)]]
vim.cmd[[nmap <silent><leader>jt <Plug>(coc-type-defination)]]
vim.cmd[[nmap <silent><leader>ji <Plug>(coc-impelmentation)]]
vim.cmd[[nmap <silent><leader>jr <Plug>(coc-references)]]
vim.cmd[[nmap <silent><leader>a <Plug>(coc-codeaction)]]
